### ISSUE TITLE
Error Reason: Could not open library

### ISSUE THREAD

**Issue by ggpabuk** [Vurv78/Autorun-rs#4]
thread '<unnamed>' panicked at 'Path DLL tried to load: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\lua_shared.dll, Error Reason: Could not open library: Module not found. (os error 126). Report this on github.', src\lib.rs:82:25

**Comment by ggpabuk** [comment]
I think there is an error in the code, because this file located in `C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin`

**Comment by Vurv78** [comment]
Thanks for making an issue, this would be fixed by using rglua which depends on #1, which could take a while.

Depending on how much you need it I could make a temporary patch and fix it in a bit tho. (This is the rglua code that made it also check for garrysmod/bin here) https://github.com/Vurv78/rglua/blob/c2b2872e201b6b440d972586ff8ff3715665c7e6/src/lib.rs#L103

**Comment by Vurv78** [comment]
Untested, lemme know if it works @ggpabuk
